version: '3.7'
services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - ./data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 1234
    ports:
      - 3306:5432
